export const REGISTER_API_START = "REGISTER_API_START";
export const REGISTER_API_SUCCESS = "REGISTER_API_SUCCESS";
export const REGISTER_API_FAIL = "REGISTER_API_FAIL";

export const LOGIN_API_START = "LOGIN_API_START";
export const LOGIN_API_SUCCESS = "LOGIN_API_SUCCESS";
export const LOGIN_API_FAIL = "LOGIN_API_FAIL";

export const LOGOUT_API_START = "LOGOUT_API_START";
export const LOGOUT_API_SUCCESS = "LOGOUT_API_SUCCESS";
export const LOGOUT_API_FAIL = "LOGOUT_API_FAIL";

export const FORGET_ADMIN_START = "FORGET_ADMIN_START";
export const FORGET_ADMIN_SUCCESS = "FORGET_ADMIN_SUCCESS";
export const FORGET_ADMIN_FAIL = "FORGET_ADMIN_FAIL";

export const GET_PROFILE_ACCOUNT_START = "GET_PROFILE_ACCOUNT_START";
export const GET_PROFILE_ACCOUNT_SUCCESS = "GET_PROFILE_ACCOUNT_SUCCESS";
export const GET_PROFILE_ACCOUNT_FAIL = "GET_PROFILE_ACCOUNT_FAIL";

export const GET_ALL_PRODUCT_START = "GET_ALL_PRODUCT_START";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
export const GET_ALL_PRODUCT_FAIL = "GET_ALL_PRODUCT_FAIL";

export const GET_DETAIL_PRODUCT_START = "GET_DETAIL_PRODUCT_START";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";
export const GET_DETAIL_PRODUCT_FAIL = "GET_DETAIL_PRODUCT_FAIL";

export const UPDATE_PROFILE_START = "UPDATE_PROFILE_START";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const UPDATE_PROFILE_RESET = "UPDATE_PROFILE_RESET";

export const UPDATE_PASSWORD_START = "UPDATE_PASSWORD_START";
export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET";

export const UPDATE_FORGOT_START = "UPDATE_FORGOT_START";
export const UPDATE_FORGOT_SUCCESS = "UPDATE_FORGOT_SUCCESS";
export const UPDATE_FORGOT_FAIL = "UPDATE_FORGOT_FAIL";
export const UPDATE_FORGOT_RESET = "UPDATE_FORGOT_RESET";

export const RESET_FORGOT_START = "RESET_FORGOT_START";
export const RESET_FORGOT_SUCCESS = "RESET_FORGOT_SUCCESS";
export const RESET_FORGOT_FAIL = "RESET_FORGOT_FAIL";
export const RESET_FORGOT_RESET = "RESET_FORGOT_RESET";

export const CLEAR_ERRORS_SUCCESS = "CLEAR_ERRORS_SUCCESS";
